import React from "react";

const SideBar = () => {
  return (
    <div className="fixed w-[400px] border border-black float-left">
      <div>Ui</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
      <div>OK</div>
    </div>
  );
};

export default SideBar;
